### ISSUE TITLE
[Bug]: MacOS 14 Sonoma Prompting multiple times for mic access

### ISSUE THREAD

**Issue by sbscomp** [sircharlo/meeting-media-manager#2229]
### What happened?

In the latest version of MacOS, when sharing the M3 media desktop over zoom, the OS prompts multiple times (possibly once for each "microphone device") to allow M3 access to the microphone. Both M3 and Zoom are already in the microphone privacy allowlist.

I was able to reproduce this on a clean install on my personal mac (which has never had M3 installed on it).

### To Reproduce

1. Run Zoom
2. Click Share Screen
3. Select the M3 Media Desktop (Usually 'desktop 2')
4. Select the "Share Audio" checkbox in zoom
5. Play a song in M3

Observed Behavior: MacOS prompts multiple times to allow Meeting Media Manager to use the microphone.

### What did you expect to happen?

I would expect to be prompted the first time on a clean install, but after that, sharing music/video over zoom should not prompt.

### Version

v23.8.1

### What platform are you seeing the problem on?

MacOS

### Relevant log output

```shell
No logs.
```

### Screenshots

The video recording is 269 MB, so I'm sharing it here as a onedrive link:

https://1drv.ms/v/s!AppW0rDGiAG_gqhOIhztkpP4Z-skeA?e=zbiirt

### Additional context

This problem does not occur under MacOS 13.x. It only started with the upgrade to MacOS 14 Sonoma.

I ensured I'm using the latest Zoom 5.16.2 (23409) on both my local desktop and our KH Mac.

**Comment by mtdvlpr** [comment]
Hi, please see #2178 for possible solutions

**Comment by sbscomp** [comment]
Re-signing the package does seem to resolve the issue here on my desktop, but feels like a hacky fix. I saw that one thread was referring to switching to a signed dependency, is that what's needed here, so that there's no need to re-sign every M3 update?

**Comment by mtdvlpr** [comment]
@sbscomp, yeah, we'd need to pay monthly in order to get M3 officially signed unfortunately...

**Comment by sbscomp** [comment]
> @sbscomp, yeah, we'd need to pay monthly in order to get M3 officially signed unfortunately...

Can you email me (my email is on my profile) in more detail on that point? I'd be willing to see if I can help with this if it can help avoid this problem (or others).

**Comment by SquareCircle99** [comment]
Yeah, I wouldn't mind pitching in some dollars if it means getting M3 signed and notarized. It's around $90 a year right?

**Comment by sbscomp** [comment]
I believe it's $99 a year for a developer account. Google's is $25 one-time fee. If you want to register it under an organization name, there's some additional verification requirements, but no additional cost.

**Comment by mtdvlpr** [comment]
An Apple developer account is $99/year and a code signing certificate for Windows applications is about $80/year

**Comment by mtdvlpr** [comment]
bump

**Comment by sbscomp** [comment]
So, circling back on this, do you feel comfortable with me starting the process for getting a developer account set up? I would be registering under my business name (registered in Illinois, USA) unless you have another preference here, and then setting up one or more of you as additional developers so you could manage releases etc.

**Comment by sircharlo** [comment]
> So, circling back on this, do you feel comfortable with me starting the process for getting a developer account set up? I would be registering under my business name (registered in Illinois, USA) unless you have another preference here, and then setting up one or more of you as additional developers so you could manage releases etc.

If I can chime in here: I really appreciate this offer. Thank you for your generosity! However, I'm not sure that I would feel comfortable with this. 

Times have truly changed since the inception of M³ many years ago. JWL's featureset keeps steadily improving! The recently released playlist feature in JWL is _very_ nice, and frankly obviates one of the main reasons why M³ came to be, that is: displaying custom media at the KH. 

I honestly see the M³ project eventually fizzling out and becoming more of a niche app, helping out in the ever-rarer scenarios where JWL isn't quite perceived as feature-complete yet. I've listed below a few of these scenarios, where JWL features are perhaps functional but complicated to use, or not implemented at all; honestly however, the list keeps shrinking.

---

### Playing background music before and after meetings
- JWL currently has no quick 'play background music' button.
- It can only shuffle predownloaded songs. It can't 'stream-shuffle' as one would expect.
- There is no "download all songs" feature. They must all be downloaded individually.
- Shuffling predownloaded songs in JWL still causes the yeartext to fade to black whenever a song ends, which is quite jarring.
- M³ is therefore quite useful for playing background music at the moment.

### Automatic preloading of media
- JWL has no mechanism to predownload all publications that will be used for a meeting, thereby allowing the media operator to quickly choose the picture or video he wants from the relevant chapter in that publication. If a publication is not already downloaded, then its media won't show up in the "Show Media" page.
- All publications must therefore be downloaded manually by the media operator and updated as needed, before every meeting.
- I'm currently evaluating if preloading publications in JWL could be automated somehow. Stay tuned.

### Automatic sharing of media for Zoom participants during hybrid meetings
- JWL currently has no integration with either Zoom or OBS Studio.
- M³ is quite useful for doing this at the moment.
- However, the Advanced Scene Switcher plugin for OBS Studio could very well replace the OBS integration that M³ has included up until now. The Advanced Scene Switcher plugin can be configured to "watch" a window (such as JWL's media presentation window) and to trigger scenes automatically based on what it sees. For example, when it sees the yeartext, activate "stage" scene. Otherwise, activate "media" scene. This would effectively render the media presentation mode in M³ obsolete!

### Syncing or sending of playlists to the media computer for playback at meetings
- There is no mechanism in JWL to fetch pre-prepared playlists from a remote server. 
- Playlists must be brought or sent to the KH computer, and then imported into JWL, usually by the media operator shortly before the meeting starts.
- A simple cloud-sync solution could be an easy fix for this: the media playlist would be created at home by the media operator or by someone assigned to this task, and then uploaded to a designated cloud provider, such as OneDrive. The media operator would then import the playlist into JWL once he arrives at the KH. Simple, and elegant.

### Easy playback of media during a Zoom-only meeting
- Sharing media for a Zoom-only meeting in JWL is clunky at best.
- Converting all non-video files into MP4 format remains the best approach for seamless sharing during Zoom-only meetings for the foreseeable future. M³ is quite useful for doing this at the moment.

---

If the above-mentioned points are the only ones that JWL can't do 'properly' or 'simply' for the moment, I would find it hard to justify pouring resources (and even time) into adding more features to M³. I'd rather think that analyzing how to patch the perceived holes in the current featureset of JWL would be the way to go, as we use JWL more and more as time goes on ,and consequently use M³ less and less.

@mtdvlpr Perhaps my view is one-sided. Thoughts?

**Comment by SquareCircle99** [comment]
I can add one more point to that list:
The macOS version of JWL is straight up the mobile version rather than a proper desktop app, and thus has no capability at all to display media on a second monitor.

**Comment by e-Feitosa** [comment]
I would add that the M3 is very stable, hardly causes crashes and the automatic sharing feature between OBS Studio + Zoom Meeting, becomes very practical, not to mention when a video ends, it is nice that the camera image returns automatically without the need to do some intervention.
