### ISSUE TITLE
[Feature]: Exclude pictures from Love People lmd brochure

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#2317]
### Is your feature request related to a problem?

It has pictures that are not necessary to show because it is just a lesson to a student.

### Describe the solution you'd like

Option to toggle like "Exclude all media from the _th_ brochure". But not all media because once a month the video should be shown

### Describe alternatives you've considered

No idea

**Comment by mtdvlpr** [comment]
Hi @dagandrew, the problem is that we can't differentiate between a talk where the picture is relevant and a demonstration where the picture isn't relevant. However, looking at JW Library, I see the picture is never included, even for talks.

We strive to imitate JW Library by default and offer extras through the settings, so I think we'll ignore the pictures by default and have a toggle to include them in the settings.

@sircharlo, thoughts?

**Comment by sircharlo** [comment]
> Hi @dagandrew, the problem is that we can't differentiate between a talk where the picture is relevant and a demonstration where the picture isn't relevant. However, looking at JW Library, I see the picture is never included, even for talks.
> 
> We strive to imitate JW Library by default and offer extras through the settings, so I think we'll ignore the pictures by default and have a toggle to include them in the settings.
> 
> @sircharlo, thoughts?

Agreed that we try to imitate JWL when possible. However, I see the _lmd_ media in mine:

![image](https://github.com/sircharlo/meeting-media-manager/assets/1275666/b7c66377-743f-41c7-9d5c-41c7210331a0)

![image](https://github.com/sircharlo/meeting-media-manager/assets/1275666/ae3a3b87-d2ac-4dd6-9bac-e36f9bf2e80f)

**Comment by mtdvlpr** [comment]
@sircharlo, you're right. I was looking inside the meeting workbook instead of at the meetings tab.

**Comment by dagandrew** [comment]
thank you, I understand
