### ISSUE TITLE
[Bug]: unable to import files with almost the same name

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3281]
### What happened?

Only one file was imported. Maybe it happened because the file name was more than 100 characters long and it thinks that it's the same name but in my case the name was almost the same, and only Part 1 and Part 2 was different.

### To Reproduce

1. Go to 'Import', then Media Files or drag and drop the files with almost the same name
2. Upload
3. See that only one of them is there

### What did you expect to happen?

Both files to be saved

### Version

24.11.1

### What platform are you seeing the problem on?

Windows

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
This is possibly happening because extremely long filenames and paths are trimmed. The filename and path length limit is a filesystem limitation, unfortunately.
Maybe what we could do is to remove a few extra characters from a path that was trimmed, and add a unique suffix. This would prevent this specific issue.

---

Example: 

- Original filename: `This is a really long filename that should get trimmed automatically.jpg`
- Current trimmed result: `This is a really long filename that sh.jpg`
- Proposed trimmed result: `This is a really long filename th_0rS4.jpg`

- Original filename: `This is a really long filename that should get trimmed automatically 2.jpg`
- Current trimmed result: `This is a really long filename that sh.jpg` <- Same as first file!
- Proposed trimmed result: `This is a really long filename th_Hxo6.jpg`

**Comment by mtdvlpr** [comment]
> This is possibly happening because extremely long filenames and paths are trimmed. The filename and path length limit is a filesystem limitation, unfortunately. Maybe what we could do is to remove a few extra characters from a path that was trimmed, and add a unique suffix. This would prevent this specific issue.
> 
> Example:
> 
>     * Original filename: `This is a really long filename that should get trimmed automatically.jpg`
> 
>     * Current trimmed result: `This is a really long filename that sh.jpg`
> 
>     * Proposed trimmed result: `This is a really long filename th_0rS4.jpg`
> 
>     * Original filename: `This is a really long filename that should get trimmed automatically 2.jpg`
> 
>     * Current trimmed result: `This is a really long filename that sh.jpg` <- Same as first file!
> 
>     * Proposed trimmed result: `This is a really long filename th_Hxo6.jpg`

@mtdvlpr, that's exactly what I'm currently testing locally!

**Comment by sircharlo** [comment]
> > This is possibly happening because extremely long filenames and paths are trimmed. The filename and path length limit is a filesystem limitation, unfortunately. Maybe what we could do is to remove a few extra characters from a path that was trimmed, and add a unique suffix. This would prevent this specific issue.
> > Example:
> > ```
> > * Original filename: `This is a really long filename that should get trimmed automatically.jpg`
> > 
> > * Current trimmed result: `This is a really long filename that sh.jpg`
> > 
> > * Proposed trimmed result: `This is a really long filename th_0rS4.jpg`
> > 
> > * Original filename: `This is a really long filename that should get trimmed automatically 2.jpg`
> > 
> > * Current trimmed result: `This is a really long filename that sh.jpg` <- Same as first file!
> > 
> > * Proposed trimmed result: `This is a really long filename th_Hxo6.jpg`
> > ```
> 
> @sircharlo, that's exactly what I'm currently testing locally!

What's that saying about great minds? 😆

**Comment by mtdvlpr** [comment]
Implemented in c04f7d3764fcede46fb5731936911f0974ba9474
