### ISSUE TITLE
[Feature]: Replacement of the icon for an active media display for Windows/Mac OS bars

### ISSUE THREAD

**Issue by mrtavor** [sircharlo/meeting-media-manager#3570]
### What happened?

-

### To Reproduce

-

### What did you expect to happen?

-

### Version

24.11.5

### What platform are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/6aba7936-72db-4b1b-892a-1ca389c02006)

### Additional context

A second icon was created to represent the second screen in the bottom bar for Windows/Mac OS. This icon matches the app’s style and clearly indicates its purpose. Additionally, the Windows icon was modified by adding more rounding. This ensures uniformly rounded corners across all platforms, contributing to a more cohesive style and looking equally good on both Windows and Mac OS.

All the originals can be found in the project on Figma.

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
Thank you for your work! Do the Windows icons comply with the [Windows app icon specs](https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-design?source=recommendations#design-guidance-shape)?

**Comment by mtdvlpr** [comment]
Also, the exported Windows icon has a size of 512x513. I think it's due to a small mismatch in the rectangle:

![image](https://github.com/user-attachments/assets/6d5c2934-66e8-4533-ab94-a7d50f202c6d)

Is this on purpose?

**Comment by ux-git** [comment]
> The same applies to the macOS icon. Is this on purpose?

That's most likely a Figma bug that causes slightly wrong exported image size when the frame is positioned on the frame with X/Y axis decimals. Try to export it once again and let us know if that helps.

> Altough uniformity is important, we should align the icon with each platforms specific requirements.

Well, Microsoft's design guides are pretty clear, however we have at least three reasons to adjust the corner radius despite the 2px requirement:

1. They allow themselves to ignore them in certain cases. Take a look at the folder icon – it's 4px radius for every corner, while most of other icons do indeed have 2px radius: 
![photo_2024-11-29 11 04 03](https://github.com/user-attachments/assets/0789ea13-a433-477d-a7f0-31ab2ed2aaa4)
Therefore putting the M³ near this icon, you can clearly see the difference, and honestly even 4px is already better: <img width="1094" alt="Screenshot 2024-11-29 at 10 56 42" src="https://github.com/user-attachments/assets/6961e7d2-000a-4839-bd3d-4972cb214009">

2. Just take a look at the Zoom icon on Windows 😆 It's not a good example to follow, but seems like Microsoft has no plans to ban Zoom on the Windows, hehe: 
<img width="918" alt="Screenshot 2024-11-29 at 11 08 28" src="https://github.com/user-attachments/assets/a2461213-1c70-42b6-a879-8c1ab57e8ee0">


3. The M³ is used mostly **not** on ultra-modern 4K displays that properly display the 2px radius. Instead on 720p and 1080p displays all that targeted 2px radius simply becomes a single pixel, making the icon just a sharp square. 

That's why we propose to increate the corner radius on Windows as well, because while testing the app in the Kingdom Hall on brand-new 1080p display the icon was visually simply square-shaped. So the first suggestion would be to increase the radius to 4px to make at least some visual difference between sharp and rounded corners, and the next option would be to inherit the macOS radius, which would be near 9px, or we can set the 8px to make it more correct, while still making the app icon consistent across platforms. Considering that Microsoft provides guidelines as a good starting point for overall consistency, I think that the radius is a matter of app devs choice. Moreover, the icon of Meeting Media Manager is already better than 90-ish% of all the Windows apps, that completely ignore the guidelines, design taste or even using the old 16x16px icon scaled up resulting in the Minecraft-style icon in 2024 😁 @sircharlo what direction would you pick?

**Comment by mtdvlpr** [comment]
> That's most likely a Figma bug that causes slightly wrong exported image size when the frame is positioned on the frame with X/Y axis decimals. Try to export it once again and let us know if that helps.

The Windows icons are now correctly sized! The macOS icons are still off: 1666x1664.

> Well, Microsoft's design guides are pretty clear, however we have at least three reasons to adjust the corner radius despite the 2px requirement:

Thank you for explaining it so clearly! I that case, I'm all for it. I prefer the 4px radius over the 2px radius as well :)

**Comment by ux-git** [comment]
> The macOS icons are still off: 1666x1664.

And now? I found and fixed one more decimal-position layer

**Comment by mtdvlpr** [comment]
> > The macOS icons are still off: 1666x1664.
> 
> And now? I found and fixed one more decimal-position layer

Am I supposed to export the 1024x1024 box with the spacing around the icon or the 832x832 box with the icon filling the entire box?

**Comment by ux-git** [comment]
@mtdvlpr [yes](https://github.com/sircharlo/mmm-refactor/issues/19#issuecomment-2187069433), the 1024px container

**Comment by ux-git** [comment]
Yes, pretty much. Figma doesn't have the built-in .ico export if you need it. You can use a plugin in the Figma to do so, or let me know and I'll export them for you

**Comment by mtdvlpr** [comment]
I have updated all assets. If you could verify for me, that be great! They're located [here](https://github.com/sircharlo/meeting-media-manager/tree/master/src-electron/icons). A test build is underway [here](https://github.com/sircharlo/meeting-media-manager/actions/runs/12085248311).

**Comment by mtdvlpr** [comment]
> Yes, pretty much. Figma doesn't have the built-in .ico export if you need it. You can use [any of the available plugins](https://www.figma.com/community/plugin/742318143106037364) in the Figma to do so, or let me know and I'll export them for you

I think I lack permissions to use plugin in the figma file. I've used the [Quasar Icon Genie](https://quasar.dev/icongenie/introduction). Let me know if the icons are not correctly generated.

**Comment by ux-git** [comment]
@mtdvlpr the macOS one looks great. @mrtavor will take a look on his Windows machine and will provide his feedback soon

**Comment by mrtavor** [comment]
![image](https://github.com/user-attachments/assets/2f6e30cd-5b7d-4dd1-8ce2-bf08c7c3fb3e)

**Comment by sircharlo** [comment]
This looks great! Thank you so much @mrtavor !!
