### ISSUE TITLE
[Bug]: Multiple-paragraphs badge for images

### ISSUE THREAD

**Issue by ux-git** [sircharlo/meeting-media-manager#3842]
### What happened?

I was waiting for this rare case to happen for ages, and here we are 😁

### To Reproduce

1. Open this week's weekend meeting
2. Take a look at the image

### What did you expect to happen?

To have a badge with '7, 11, 15'

### Version

v24.12.2

### What platform are you seeing the problem on?

macOS

### Screenshots

<img width="203" alt="Screenshot 2024-12-26 at 11 27 42" src="https://github.com/user-attachments/assets/6de46ebc-1218-4a78-b796-45e1f70fd124" />

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
Change the meeting day to any other day, then change it back to the desired day. Did this solve the issue?

**Comment by ux-git** [comment]
Yes, right away after changing the meeting day the badge appeared. 

<img width="168" alt="Screenshot 2024-12-26 at 13 19 28" src="https://github.com/user-attachments/assets/e605fc87-fb84-43a2-a1a7-94ceef0f9672" />

**Comment by sircharlo** [comment]
This is because I changed the way paragraph numbers are stored a few updates back, to allow for the enhanced numbers we now see. As a result, weeks that were already fetched when a user installed that specific update (for most users, 4 weeks) won't display certain paragraphs properly, since the ones that were already fetched were in the 'old' format.
Workaround: change the meeting day temporarily, like I mentioned.

**Comment by ux-git** [comment]
@sircharlo gotcha. Then for the next similar case later, it should work fine. Thank you!
