### ISSUE TITLE
The italics in the translation is not working

### ISSUE THREAD

**Issue by joaochris** [sircharlo/meeting-media-manager#523]
![image](https://user-images.githubusercontent.com/76891864/198144714-fd16469c-5b3e-4b26-8ddb-c700a5f9ad65.png)

Why do some words I've italicized not stay?

@sircharlo 
@mtdvlpr

**Comment by mtdvlpr** [comment]
That would be because the default is not to render html unless explicitly configured. It's a security thing. Someone could for example write harmful html in a translation string or user input and that would then be rendered as html. The places where the English strings have html (<em>...</em>) are explicitly configured to render the string as html.

**Comment by sircharlo** [comment]
Correct. 
I'm not sure I see the need for italics in this particular context.

**Comment by joaochris** [comment]
I understood. I thought about it :), that it would only work if I had the strings in English. Thanks!
