### ISSUE TITLE
OBS shows black screen because Window Capture broke with M³ update

### ISSUE THREAD

**Issue by wifilogo** [sircharlo/meeting-media-manager#546]
### Describe the bug
Yesterday, after automatic 22.10.1 update and **the meeting had started**, Zoom attendees only saw a black screen. It was a serious problem that we saved by sharing the screen in the traditional way. At the Kingdom Hall the attendees had no problem.
**WE NEED A _Disable Automatic Updates_ BUTTON** to test the changes at home beforehand and not have problems once the meeting has started.

### How we have solved the bug TODAY AT HOME
We have created a new MONITOR scene in OBS Studio and it has started to work correctly.
We will try to update to obs-websocket v5 and see if it works fine at Kingdom Hall too.

**Thank you very much for your wonderful work.**

### System specs
- Windows_NT 10.0.19045 (In Windows 11 same behavior)
- M³ v22.10.1

### Anonymized `prefs.json`
```
{
  "app": {
    "autoOpenFolderWhenDone": false,
    "autoQuitWhenDone": false,
    "autoRunAtBoot": false,
    "autoStartSync": true,
    "congregationName": "HomeTest",
    "disableHardwareAcceleration": false,
    "localAppLang": "es",
    "localOutputPath": "***",
    "obs": {
      "enable": true,
      "port": "***",
      "password": "***",
      "mediaScene": "MONITOR_2",
      "cameraScene": "LifeCam_HD",
      "useV4": true
    },
    "offline": false,
    "outputFolderDateFormat": "YYYY-MM-DD",
    "theme": "system",
    "ppEnable": true
  },
  "cong": {
    "server": "***",
    "port": "***",
    "user": "***",
    "password": "***",
    "dir": "***"
  },
  "media": {
    "enableMediaDisplayButton": true,
    "enableMp4Conversion": false,
    "enablePp": false,
    "enableVlcPlaylistCreation": true,
    "excludeLffi": true,
    "excludeLffiImages": true,
    "excludeTh": true,
    "hideMediaLogo": false,
    "hideWinAfterMedia": false,
    "keepOriginalsAfterConversion": false,
    "lang": "S",
    "langUpdatedLast": "2022-10-30T05:01:07.796Z",
    "maxRes": "720p",
    "mediaWinShortcut": "Alt+Z",
    "ppBackward": "PageUp",
    "ppForward": "PageDown",
    "preferredOutput": "window",
    "presentShortcut": "Alt+D"
  },
  "meeting": {
    "enableMusicButton": true,
    "enableMusicFadeOut": false,
    "musicFadeOutTime": 5,
    "musicFadeOutType": "smart",
    "musicVolume": 100,
    "mwDay": 3,
    "mwStartTime": "19:00",
    "shuffleShortcut": "Alt+K",
    "specialCong": false,
    "weDay": 5,
    "weStartTime": "18:30"
  },
  "__internal__": {
    "migrations": {
      "version": "22.10.1"
    }
  }
}
```

**Comment by mtdvlpr** [comment]
Sorry to hear this happened! We can definitely add a disable auto updates setting. Might I ask some more details to prevent similar issues happening in the future? How many OBS scenes do you have? Did the OBS scene "MONITOR" show the camera correctly in OBS itself? Was the OBS scene correctly switched to the "MONITOR" scene when selecting it? I'm trying to pinpoint the problem, because to me it sounds like either Zoom had selected the wrong camera (not the OBS virtualcam) or the OBS scene itself was incorrectly configured (which would be the case if it showed a black screen in OBS itself as well).

**Comment by mtdvlpr** [comment]
Option to disable auto updates has been added with commit f2821e1a88188812989e9555ea2b22ba4a9beddc

**Comment by wifilogo** [comment]
> @wifilogo, sorry to hear this happened! We can definitely add a disable auto updates setting. Might I ask some more details to prevent similar issues happening in the future? How many OBS scenes do you have? Did the OBS scene "MONITOR" show the camera correctly in OBS itself? Was the OBS scene correctly switched to the "MONITOR" scene when selecting it? Did you get a warning that either the configured media or camera scene didn't exist anymore? I'm trying to pinpoint the problem, because to me it sounds like either Zoom had selected the wrong camera (not the OBS virtualcam) or the OBS scene itself was incorrectly configured (which would be the case if it showed a black screen in OBS itself as well).

In my HP laptop, same problem.
Restarting the laptop doesn't solve the problem.
Updating OBS Studio to 28.0.3 with websocket v5 doesn't solve the problem either.
The OBS scene switched correctly.
It only gets fixed when I **_delete my MONITOR scene_** and recreate it.
Then, all works fine.

My laptop screnshots:

![M3_1](https://user-images.githubusercontent.com/11198837/199027535-702ea1bc-d8b4-4110-babf-06cb4456d6c2.jpg)

![M3_2](https://user-images.githubusercontent.com/11198837/199027556-988cfc7e-ceab-4dc2-8019-e8b717f828c1.jpg)

![M3_3](https://user-images.githubusercontent.com/11198837/199027590-b05e870f-4b0d-450a-8b3f-5b720ba8eb51.jpg)

![M3_4](https://user-images.githubusercontent.com/11198837/199027608-a53956c7-c8fb-48b3-8cc1-7fc32807bdc3.jpg)

Thank you.

**Comment by mtdvlpr** [comment]
And what happens when you select the media scene from OBS directly? Without playing anything. My guess is a black screen. If that's the case, it means that your media scene is wrongly configured in OBS. M3 is not to blame. M3's only responsibility is to set the current scene to the media scene.

**Comment by wifilogo** [comment]
Will that.
But with M3 22.8 it worked fine.
And with M3 22.10 it stopped doing it.
I will try disabling automatic updates to avoid problems at the beginning of the meeting.
:)

**Comment by mtdvlpr** [comment]
I see you're using a window capture if I'm not mistaken. It might be that the window you have configured doesn't exist anymore, because everytime you restart M3 a new window opens. Try using a screen capture (with 2nd monitor).

**Comment by wifilogo** [comment]
Thanks.
I will try it in KH.

**Comment by mtdvlpr** [comment]
So, I managed to recreate your issue. What I did was set up the window capture by seleting the window called 'media window - m3'. Then I changed the title of the window to 'new media window - m3'. Now OBS can't find the window with the original name and displays a black screen. This is what happened, because with the major update 22.9.0, the media window got a slightly different name. 2 ways of fixing this:
- Since a name change is unlikely to happen again in the near future, you're save to keep a window capture, once you've reconfigured it.
- You can switch to a screen capture (when the media window is full screen on an external monitor)
![image](https://user-images.githubusercontent.com/46671786/199035157-05ac228b-6f27-45c2-bda9-4811085bfd66.png)

**Comment by wifilogo** [comment]
Thank you very much for your help.
