### ISSUE TITLE
[BUG] lff media is included for 5-min bible studies

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/meeting-media-manager#874]
**Describe the bug**
When a bible study for the apply yourself portion of the midweek meeting includes images/videos in the referenced lff lesson, they are included in the media list. Since the instructions specify that such videos are not to be played during the assignment but merely referenced, they should preferably not be included in the media list.

**To Reproduce**

1. Go to 'December 26 - January 1'
2. Click on 'Fetch media'
3. Do 'Open presentation mode'
4. See 'Jehovah has done so much for me' video

**Expected behavior**
The media referenced for a 5-min bible study should be ignored

**System specs (please complete the following information):**

- OS: All
- App Version: 22.12.1

**Additional context**
@sircharlo, since you have more knowledge about the fetching logic, maybe you know an easy fix for this. The only solution I can think of is comparing the paragraph numbers of all referenced lff media and only using the media of the latest paragraph (since that's the congregation bible study).

**Comment by sircharlo** [comment]
There it is! That's why I had disabled it in the previous version, now I remember. 
Related to #744 and #745. 
There's no easy fix here from a "logic" point of view here from what I can see. Media from refs can either be processed (like what was needed in #744) or not (like for the 5 min. talk during the week of Dec. 26-Jan 1st).
The only thing I can think of would be to ignore _videos_ for ref media (as videos to be shown during a meeting will always be linked to "directly", not from refs), while processing _images_ normally (sometimes, images from refs are used by speakers/students and can contain useful information).

**Comment by mtdvlpr** [comment]
I'm confused. Isn't it only supposed to do that for internal refs of internal refs. The lff book isn't an internal ref, right?

**Comment by sircharlo** [comment]
No, **I'm** confused. 😕 
#744 was _[checks]_ media from a `Document` referred to from an `InternalLink`.
This current issue is _[adjusts glasses]_ a video being fetched from a `Document` referred to from the `Extract` table. The problem is that this is exactly the same was that the CBS media gets fetched.

**Comment by sircharlo** [comment]
Programmatically, there's no way to distinguish from `Extract` numbers 76 and 79...

![image](https://user-images.githubusercontent.com/1275666/208487608-4e940648-d215-41e0-8a87-b6c58f5b2cea.png)

**Comment by mtdvlpr** [comment]
Yeah, that's what I thought! But we do provide the 2 with a different paragraph number. The cbs has par nr 8 and the bible study would have par nr 5 for example. Maybe that can be used to **safely** distinguish between the two. We should make sure that this will always work as intended, since it's a bit of a dirty trick

**Comment by sircharlo** [comment]
Yeah, some sort of "get `number of paragraphs` in main document":
![image](https://user-images.githubusercontent.com/1275666/208489286-9c047384-ad16-439f-8e49-45899113582c.png)

Combined with "only include videos from current `Extract` if paragraph number of `Extract` is gte `number of paragraphs` minus 4":

![image](https://user-images.githubusercontent.com/1275666/208488894-256a1a79-e69b-4a06-b3bb-2d4c918f51b2.png)

Like you said, it's a dirty trick, but it would work.

**Comment by mtdvlpr** [comment]
Yeah, btw, what do you use to get this UI for the jwpub database?

**Comment by sircharlo** [comment]
> Yeah, btw, what do you use to get this UI for the jwpub database?

https://sqlitebrowser.org/dl/ - Free and cross-platform!

**Comment by e-Feitosa** [comment]
Here it continued to download the Study media normally (5min). A suggestion, would be in the main operation panel (view the media) have the option to delete a media that was downloaded more. Like an X in the image or video to hide or exclude from the list.

![image](https://user-images.githubusercontent.com/90984283/210284858-6d1a1f9a-d2e1-4460-83ee-574ee162230f.png)
